In [20]:
import numpy as np
import scipy

Question 2a

In [15]:
Objlens = np.matrix(([1,0],[-1/100,1]))
Gap = np.matrix(([1,75],[0,1]))
Neglens = np.matrix(([1,0],[1/60,1]))
ObjDis = np.matrix(([1,1e6],[0,1]))

In [12]:
lensmatrix = Neglens*Gap*Objlens
print (lensmatrix)

[[ 2.50000000e-01  7.50000000e+01]
 [-5.83333333e-03  2.25000000e+00]]


question 2b

In [16]:
sysmatrix = lensmatrix*ObjDis
print (sysmatrix)

[[ 2.50000000e-01  2.50075000e+05]
 [-5.83333333e-03 -5.83108333e+03]]


In [27]:
ImgDis = np.matrix(([1,42.88654195],[0,1]))

In [28]:
sysmatrix = ImgDis*lensmatrix*ObjDis
print (sysmatrix)

[[-1.71494708e-04  1.10541693e-05]
 [-5.83333333e-03 -5.83108333e+03]]


2c

In [29]:
ObjLensR = 22
NeglensR = 12

In [31]:
AperStop = ImgDis*Neglens*Gap
print (AperStop)

[[1.71477570e+00 1.71494719e+02]
 [1.66666667e-02 2.25000000e+00]]


In [34]:
a1=ObjLensR/AperStop[0,1]
print (a1)

0.12828383333652396


In [35]:
AperStop = ImgDis
print (AperStop)

[[ 1.         42.88654195]
 [ 0.          1.        ]]


In [36]:
a2 = a1=NeglensR/AperStop[0,1]
print (a2)

0.27980805759509364


In [37]:
exitpup = Neglens
print(exitpup)

[[1.         0.        ]
 [0.01666667 1.        ]]


In [39]:
expupimage = -(Gap[0,1]*exitpup[0,0]+exitpup[0,1])/(Gap[0,1]*exitpup[1,0]+exitpup[1,1])
print(expupimage)

-33.333333333333336
