In [1]:
import numpy as np
import math

Question 2

In [6]:
lens1 = np.matrix([[1,0],[-1/100,1]])
gap1 = np.matrix([[1,75],[0,1]])
lens2 = np.matrix([[1,0],[1/60,1]])

In [7]:
M_sys = lens2*gap1*lens1

In [8]:
print(lens1)
print(gap1)
print(lens2)
print(M_sys)

[[ 1.    0.  ]
 [-0.01  1.  ]]
[[ 1 75]
 [ 0  1]]
[[1.         0.        ]
 [0.01666667 1.        ]]
[[ 2.50000000e-01  7.50000000e+01]
 [-5.83333333e-03  2.25000000e+00]]


In [11]:
matrix1 = np.matrix([[1,1000000-75],[0,1]])

In [12]:
alpha0_1 = abs(11/matrix1[0,1])

In [13]:
print(alpha0_1)

1.1000825061879641e-05


In [14]:
matrix2 = gap1*lens1*matrix1

In [17]:
print(matrix2)

[[ 2.5000000e-01  2.5005625e+05]
 [-1.0000000e-02 -9.9982500e+03]]


In [15]:
alpha0_2 = abs(6/matrix2[0,1])

In [16]:
print(alpha0_2)

2.3994601214726686e-05
